[package]
name = "commit_checker"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
regex = "1.12.2"
spinoff = "0.8.0"
oxc = { version = "0.102.0", features = ["semantic"] }
oxc_semantic = { version = "0.102.0", features = ["linter"] }
line-numbers = "0.4.0"
rustc-hash = "2.1.1"
